#!/usr/bin/env bash
#!/bin/bash
while IFS=: read -r username password userid groupid comment homedir shell; do
    echo "The user ${username} is part of the ${groupid} gang, lives in ${homedir} and rides ${shell}. ${userid}'s place is protected by the passcode ${password}, more info about the user here: ${comment}"
done < /etc/passwd

