#!/usr/bin/env bash
# Script that counts occurrences of IPs and HTTP codes in apache log

awk '$1 && $9 ~ /^[0-9]+$/ {count[$1" "$9]++} 
END {if (length(count) > 0) 
        system("awk '\''BEGIN{for(k in count) print count[k], k}'\''")}' apache-access.log

