#!/bin/bash
echo $(( $(echo $WATER | tr 'ewatr' '01234' | awk '{s=0; for(i=1;i<=length;i++) s=s*5+substr($0,i,1); print s}') + $(echo $STIR | tr 'ti.r' '0123' | awk '{s=0; for(i=1;i<=length;i++) s=s*4+substr($0,i,1); print s}') )) | awk '{b="shtbeolhc";n=$1;out="";while(n>0){out=substr(b,(n%8)+1,1)out;n=int(n/8)}; print out}'
