#!/usr/bin/env bash
# Init script to manage manage_my_process process: start, stop, restart

PID_FILE="/tmp/my_process.pid"
SCRIPT_PATH="$(pwd)/manage_my_process"

start() {
    "$SCRIPT_PATH" &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    if [ -f "$PID_FILE" ]; then
        kill "$(cat "$PID_FILE")" 2>/dev/null
      sudo  rm -f "$PID_FILE"
    fi
    echo "manage_my_process stopped"
}

restart() {
    if [ -f "$PID_FILE" ]; then
        kill "$(cat "$PID_FILE")" 2>/dev/null
        rm -f "$PID_FILE"
    fi

    "$SCRIPT_PATH" &
    echo $! > "$PID_FILE"

    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
